### ISSUE TITLE
Remove the astropy-helpers submodule

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#107]
Details here:

https://github.com/astropy/astropy-APEs/blob/ecb943c3f87dce1a97d3f25902ea827e379c5a7c/APE17.rst

**Comment by pllim** [comment]
APE 17 is accepted. Look out for a "conversion guide" that Tom Robitaille will post to astropy dev mailing list.

**Comment by karllark** [comment]
Yep.

**Comment by karllark** [comment]
Done in #159.
