### ISSUE TITLE
TypeError: object of type 'float' has no len() when calling CCM89.evaluate()

### ISSUE THREAD

**Issue by sohamvg** [karllark/dust_extinction#108]
This is my log:
`>>> CCM89.evaluate(0.7*u.micron,1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/soham/.local/lib/python2.7/site-packages/dust_extinction/parameter_averages.py", line 100, in evaluate
    n_x = len(x)
TypeError: object of type 'float' has no len()`

When I looked in dust_extinction/parameter_averages.py/ , we have x = _get_x_in_wavenumbers(in_x) which is indeed a float, right?

**Comment by sohamvg** [comment]
The error was coming because of the input format was wrong.I figured that evaluate() takes array as input. So when I changed to 
`CCM89.evaluate([0.7*u.micron],1.0)`
the code worked fine.

**Comment by karllark** [comment]
Thanks for opening an issue on this topic - very much appreciate the feedback.

Yes, changing the input format to be a list/array will allow the code to produce the right answer.  But it would be nice if this was not required.  I'm going to reopen the issue and investigate how to have the code able to handle both types of input.

**Comment by sohamvg** [comment]
Alright, I am also trying to look for a solution.
