### ISSUE TITLE
v0.9 release?

### ISSUE THREAD

**Issue by pllim** [karllark/dust_extinction#142]
With v0.8 (the latest released version from PyPI as of 2020-02-20), I see this warning that I think has been fixed in `master`. When will there be a v0.9 release? Thanks!

```python
>>> from dust_extinction.parameter_averages import CCM89
>>> ext = CCM89(Rv=3.1)
```
```
WARNING: AstropyDeprecationWarning: Class CCM89 defines class attributes ``inputs``.
            This has been deprecated in v4.0 and support will be removed in v4.1.
            Starting with v4.0 classes must define a class attribute ``n_inputs``.
            Please consult the documentation for details.
             [astropy.modeling.core]
```

**Comment by karllark** [comment]
Yes.  I have one or two other things I want to get in for the next release.  Will push forward on getting this done.  Thanks for the push.

**Comment by lea-hagen** [comment]
I'm wondering the same thing - I'm setting up an environment for the BEAST, and it would be nice to install from conda/pip instead of doing `pip install git+https://github.com/karllark/dust_extinction.git`.

**Comment by karllark** [comment]
I've got one more update I'd like to do and then v0.9 will be ready.  Very close.  Maybe next week?

**Comment by lea-hagen** [comment]
Awesome!

**Comment by karllark** [comment]
v0.9 released.
