### ISSUE TITLE
AttributeError: 'G16' object has no attribute 'Rv'

### ISSUE THREAD

**Issue by bkornpob** [karllark/dust_extinction#179]
I was trying to use G16 model for the SMC dust extinction. The program dust-extinction version = 1.0. Here is the minimal example, and error message.

```
from dust_extinction.parameter_averages import G16
ext = G16(RvA=Rv,fA=fA)
t = ext.extinguish(wavelengths,Ebv=Ebv)
```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-30-83c5cae74309> in <module>
> ----> 1 ext.extinguish(wavelengths,Ebv=Ebv)
> 
> ~/anaconda3/envs/astroconda202104/lib/python3.7/site-packages/dust_extinction/baseclasses.py in extinguish(self, x, Av, Ebv)
>      50         # if Av is not set and Ebv set, convert to Av
>      51         if Av is None:
> ---> 52             Av = self.Rv * Ebv
>      53 
>      54         # return fractional extinction
> 
> AttributeError: 'G16' object has no attribute 'Rv'

**Comment by karllark** [comment]
Thanks for opening this issue.  Should be a quick fix. Will try and work on this in the next few days.

**Comment by bkornpob** [comment]
@karllark , thank you very much. Did you update for the fix?

**Comment by karllark** [comment]
Thanks for the reminder.  See PR #180.
