### ISSUE TITLE
Astropy's update_default_config is now depracated

### ISSUE THREAD

**Issue by WillJRoper** [karllark/dust_extinction#197]
**Bug:**

Importing `dust_extinction` causes an immediate error in `_astropy_init`. Here is the error trace from our workflow:

```
src/synthesizer/dust/attenuation.py:6: in <module>
    from dust_extinction.grain_models import WD01
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dust_extinction/__init__.py:6: in <module>
    from ._astropy_init import *   # noqa
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dust_extinction/_astropy_init.py:21: in <module>
    from astropy.config.configuration import (
E   ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' (/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/astropy/config/configuration.py)
```
**The cause:**

The latest release of Astropy (released yesterday, 28/11/23) has removed the deprecated `update_default_config` function. 

**The solution:**

In short, I don't know, but the Astropy changelog lists this removal as having no replacement since it is "no longer needed". I must admit I'm not deeply familiar with the Astropy API but there must be a way of avoiding using this function if it was removable without replacement.

**Comment by karllark** [comment]
Yes, I have seen this with another repository.  Will try and figure out what the issue is so it can be solved.

**Comment by WillJRoper** [comment]
Amazing! Let me know if we can provide any help, happy to get stuck in.

**Comment by karllark** [comment]
Was fairly straightforward to fix.  Used the docs in https://packaging-guide.openastronomy.org/en/latest/ to see the issue.  Also needed to update a few other things.  And will need to do another PR as I was a bit hasty in merging.  The other PR is just to make things even better for the init and for tox.

**Comment by karllark** [comment]
I do need to release a new version for pip.  I see I need this for tests in a different package (measure_extinction).

Will do this ASAP, but want to include two new extinction curves.  See issue #200.

**Comment by WillJRoper** [comment]
Funnily enough, we have an issue sitting on our (fledgling) package including one of those dust curves (https://github.com/flaresimulations/synthesizer/issues/332). 

No rush but good to hear it's being implemented! 

We temporarily fixed the issue by pinning our Astropy dependency but I'll keep an eye out for a release on your side (and resolution of #200) before lifting that pin.

**Comment by karllark** [comment]
New version released.  v1.3.  Please confirm this fixes the issue.  It did for my other package.

**Comment by WillJRoper** [comment]
Indeed, all fixed up. Thanks
