### ISSUE TITLE
Citation guidelines

### ISSUE THREAD

**Issue by mdecleir** [karllark/dust_extinction#206]
We should add some guidelines in the GitHub readme, and in the readthedocs on how to cite the package and the papers related to the different curves in the package.
Also, some more information on when to use what curve would likely be appreciated by the users.

**Comment by karllark** [comment]
Thanks for the comment.  Great to hear others find it useful.  Definitely helps keep my motivation up for this work.

Will work on the citation info.  And try to put together a JOSS article for the repository itself (been on my todo list for way too long).
