### ISSUE TITLE
Paper JOSS review: State of Field

### ISSUE THREAD

**Issue by keflavich** [karllark/dust_extinction#217]
As part of the JOSS review, there is a checklist item:
" State of the field: Do the authors describe how this software compares to other commonly-used packages?"

I don't think this is covered in the current draft.  Are there any other packages that implement these commonly-used extinction curves?  If not, I'd recommend noting that.

I would also recommend referencing your own dust-attenuation package, since you specifically call out the attenuation/extinction distinction.

**Comment by karllark** [comment]
Done in a recent commit.

Did this to the master directly by mistake - haven't done this in a long time.  Mondays!

**Comment by karllark** [comment]
There is only one package that is similar to this one and that has been maintained in recent years, and this is now referenced in the paper.

**Comment by karllark** [comment]
Please close this issue if you agree with my changes.

**Comment by keflavich** [comment]
Could you link the commit here?

**Comment by keflavich** [comment]
https://github.com/karllark/dust_extinction/commit/cb29df630954df46b2ee741f02f3416a09994f34 is the relevant one, I believe.

**Comment by karllark** [comment]
You got the correct commit of course.
