### ISSUE TITLE
Units of extinction curves

### ISSUE THREAD

**Issue by mdecleir** [karllark/dust_extinction#219]
It is not clear what units the different extinction curves are given in, e.g. A(lambda)/A(V) or E(lambda-V)/E(B-V).

I think, ideally, all curves should have the same units.

At a minimum, the units should be reported in the tables here:
https://dust-extinction.readthedocs.io/en/latest/dust_extinction/choose_model.html

**Comment by TheSkyentist** [comment]
Extinction models in this package are parametrized as A(lam)/A(V). 
So calling `model(lambda)` will return the A(lam)/A(V) values.

**Comment by karllark** [comment]
Correct.  Except for the FM90 model.  This one returns E(lambda-V)/E(B-V) as these are the units in the literature for most of the FM90 parameters reported.  Would be good to get this into the docs for sure.

**Comment by TheSkyentist** [comment]
Interesting I hadn’t realized, actually it may be useful to also highlight the differences with the "Shape" models, since these do not provide the same "extinguish" method compared to the others.

**Comment by karllark** [comment]
Good point.
