### ISSUE TITLE
Reference API Inhertance diagrams do not render

### ISSUE THREAD

**Issue by TheSkyentist** [karllark/dust_extinction#220]
Inheritance diagrams are not rendering correct at: https://dust-extinction.readthedocs.io/en/latest/dust_extinction/reference_api.html#

**Comment by karllark** [comment]
Yep.   See #214.   Will work on fixing this today.  Has happened before and I have to re-remember how to fix this.

**Comment by karllark** [comment]
No worries.  Good ping for me to get this fixed.  Straightforward fix.  See #221.
