### ISSUE TITLE
JOSS Review: Instructions on Contributing Curves and Minor Comments

### ISSUE THREAD

**Issue by TheSkyentist** [karllark/dust_extinction#222]
The purpose, documentation, and examples for the code are all well described in the JOSS submission. The code is installable, flexible, and useful for current and future astronomical analysis. 

One of the most useful parts is the vast array of extinction models available to the end user, with the ability for contributing more as stated as one of the strengths of the code in the final sentence of the draft. As this is a stated feature of the code:

1. Would it be possible to add documentation on the format required for an extinction curve that could be merged into the repository?
2. Or, equally, to add documentation to the meta-classes to enable an end user to easily create "on-the-fly" extinction curves. 

I believe that this would satisfy the Documentation Community Guidelines section of the JOSS checklist. 

In addition, I have a few minor comments on the draft around language:
1. Line 6, it might sound better by removing the first instance of word "photon". 
2. Line 30, I believe the units A(lambda) should be explicitly stated here as magnitudes. 
3. Line 36, would it be possible to change "like" to "such as", as the former sounds conversational.

**Comment by karllark** [comment]
All good suggestions.  I will work to get these done ASAP.

**Comment by karllark** [comment]
For the comments on the text of the paper.

1. I've not removed the first photon.  The reason is that with only the 2nd photon it reads as "absorbing photons out of the line-of-sight."   This is not correct.  I agree that it is a bit awkward, but it is more accurate.
2. Done.
3. Done.

**Comment by karllark** [comment]
If you find that #224 does not address this issue fully, please reopen this issue (once it is closed by merging the PR).
