### ISSUE TITLE
Inconsistent spline boundary conditions

### ISSUE THREAD

**Issue by ado8** [karllark/dust_extinction#243]
# Issue
The spline evaluation in `shapes._curve_F99_method` uses `scipy.interpolate.splrep` and `splev`, where the splrep [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splrep.html) states 
> The default boundary condition is ‘not-a-knot’, i.e. the first and second segment at a curve end are the same polynomial. More boundary conditions are available in [CubicSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline).

This is inconsistent with Fitzpatrick's [IDL routine](https://universe.gsfc.nasa.gov/archive/idlastro/ftp/pro/astro/fm_unred.pro) which uses [CSPLINE](https://github.com/wlandsman/IDLAstro/blob/master/pro/cspline.pro), which uses [SPL_INIT](https://www.nv5geospatialsoftware.com/docs/spl_init.html) with default YP0 and YP1 arguments, which ultimately results in a spline with 'natural' boundary conditions (second derivative is 0 at ends) rather than 'not-a-knot' boundary conditions.

# Severity of issue
The `_curve_F99_method` is called in the F99 and F04 dust laws.
The differences due to the boundary conditions is on the order of millimags, but varies with RV and wavelength as shown in the attached figure.
![image](https://github.com/user-attachments/assets/771ab0be-dc7b-4842-940e-e4767d11a12c)

# Proposed change
This can be fixed by replacing
```
spline_rep = interpolate.splrep(spline_x, spline_y)
axav[indxs_opir] = interpolate.splev(x[indxs_opir], spline_rep, der=0)
```
with
```
axav[indxs_opir] = interpolate.CubicSpline(spline_x, spline_y, bc_type='natural')(x[indxs_opir])
```

**Comment by karllark** [comment]
Thanks for raising this issue!  This is a detail I was not aware of.  I'll have a look and evaluate in a week or so.  Hope this is soon enough.
