### ISSUE TITLE
Change default input from wavenumber to wavelength?

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#36]

**Comment by karllark** [comment]
What wavelength unit?  Micron?  Angstrom?  
Angstrom as this is the expected unit for the fm_unred and ccm_unred functions in IDL.
Micron as this is a good unit when spanning the full UV to MIR wavelength range.

**Comment by pllim** [comment]
If you wish this to be user configurable, this default unit could be a Astropy ConfigurationItem.

**Comment by karllark** [comment]
Leaning toward micron.
@pllim : can you point me to the configureitem info?  Never heard of this before.

**Comment by pllim** [comment]
Official doc is at http://docs.astropy.org/en/stable/config/ .

**Comment by karllark** [comment]
This is not trivial to do.  I've tried, but have had issues with the fitting (e.g., FM90 fit test fails).  Not sure why.  Maybe related to the fact that the dust_extinction models currently cannot handle units for the fitting portion.  But even when I remove units, the fit do not work when x is in microns (even after the FM90 code is changed to expect this!).

**Comment by pllim** [comment]
@perrygreenfield is in the mist of refactoring `astropy.modeling`, so perhaps it would be possible after that...?

**Comment by karllark** [comment]
Going to close this.  The answer is no.  Quite non-trivial to change.  The x inputs for the models fully support units and issue a warning with the expected default when units are not passed.
