### ISSUE TITLE
Add keyword to override wavenumber/wavelength limits

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#37]
By default, enforce the limits on wavelength that are set by the range over which a model has been defined.  Allow overrides, but only with explicit setting of a keyword.

**Comment by krislars** [comment]
This becomes especially important in the infrared.  Giving the option to let the curve be tied to zero at infinite wavelength would be useful.

In addition, the Fitzpatrick & Massa (2007) paper uses wavenumbers of 0, 0.25, 0.5... explicitly, but the observations from that paper don't go beyond 2MASS K.  So I'm undecided where to call the model defined.

**Comment by karllark** [comment]
Is this needed internally in the code?  The thought I had would be to allow users to pass wavelengths outside of the defined range for the model to get extinction calculations for those wavelengths.  If it is only internal to the code (to make sure that the curve is tied to zero at infinite wavelength), then I don't think it is needed.

**Comment by krislars** [comment]
One example would be dereddening a spectrum that goes out to 4 microns.  Right now, the FM90 models are confined to wavenumbers above 0.3.  The FM07 paper lists 0.25 as a wavenumber spline point, but clearly says that the curve fits the 2MASS photometry.  So I guess my question is where do we cut it off and make the user put in a keyword.  If 4 microns is OK, what about 10 or 20 or 100?  I'm not sure what the answer is.

**Comment by karllark** [comment]
Better to use dust grain models to do the extrapolation than relaxing the limits.  See #6.
