### ISSUE TITLE
DOC: Add "Quick Start" in index.rst

### ISSUE THREAD

**Issue by pllim** [karllark/dust_extinction#44]
A "Quick Start" section in `index.rst` (main page) would be nice for someone who just discovered this package and would like to know its usage at a glance.

**Comment by karllark** [comment]
Can you give me an example of what such a section would look like?

**Comment by pllim** [comment]
Conceptually, something with a "wow" factor, that would keep me interested to read further. For example (which might or might not make sense), how do I apply or un-apply a common extinction curve to a famous galaxy? This could very well be an existing example deeper in the doc. Does this make sense?

**Comment by karllark** [comment]
Thanks for the feedback!

Note that extinction curves are not appropriate for applications like galaxies.  This would be an attenuation curve that includes the radiative effects of mixing the stars and dust together.  Extinction curves are specific to a single star behind a screen of dust.  I've opened issue (#47) to add information about extinction vs attenuation to the docs.

**Comment by krislars** [comment]
How about a jupyter notebook with pretty plots?  I could help with that.

**Comment by karllark** [comment]
@krislars I think this is a great idea.  While it does not directly address the quick start part, but examples of how to use are definitely needed.  Especially in a jupyter notebook!  I have created a new issue for this (#54).

**Comment by karllark** [comment]
I've made a start to the quick start text in the doc_update branch.

**Comment by karllark** [comment]
Pleas checkout the updated docs.  Please comment and ask for this issue to be reopened if needed.

**Comment by pllim** [comment]
That's great, @karllark ! Some minor comments:

1. It is more fool-proof (against future edits) to label the unit using `.unit` attribute.
2. Why not also label the unit for flux?

**Comment by karllark** [comment]
@pllim I do not understand your comment about labeling the unit.  Can you be more specific.

There is no requirement on the unit for the flux.  Applying the extinction is just a multiplicative factor that does not change the units.

Not 100% sure this package is fully unit supportive.  Still learning the units package and more examples, users are definitely needed!

**Comment by pllim** [comment]
@karllark 

1. In your X-axis, you hardcoded Angstrom in the label. It would be more flexible to dynamically insert that unit in the label via `.unit` attribute from the `Quantity` that is storing wavelength array. This way, in the future, if you decide to change the `Quantity` to, say, microns, you don't have to worry about updating the label manually.

2. Technically speaking, applying extinction does not change the wavelength unit either. However, the unit is in the X-axis label anyway. I just feel it would be more consistent to also label flux unit in this case. Just my OCD speaking.

**Comment by krislars** [comment]
I think what @pllim means is something like this:

ax.set_xlabel('$\lambda$ ['+str(wave.unit)+']')
ax.set_ylabel('$Flux$ ['+str(flux.unit)+']')

**Comment by pllim** [comment]
Yes, thanks, @krislars ! Although, using `.format()` would negate the need for explicit `str` casting. 😄

**Comment by karllark** [comment]
Ok.  Just fixed these and generated a new pull request #56.  Will merge once the travis testing says all is good.

**Comment by pllim** [comment]
Thanks, @karllark ! (Though I noticed the coverage fell from 100% to 99%) 😉

**Comment by karllark** [comment]
@pllim : yeah.  I think it is something I'm doing with my new union of two models and fitting.  One of the models uses analytical derivatives and one does not.  On my list to investigate.  Till then, I have to live with less than 100% coverage.  Sadness.
