### ISSUE TITLE
CCM89 with variable bump strength

### ISSUE THREAD

**Issue by lea-hagen** [karllark/dust_extinction#53]
There's a nice generalization of CCM89 in the Appendix of [Conroy+10](http://iopscience.iop.org/article/10.1088/0004-637X/718/1/184/pdf) that varies the bump strength.  Is adding that (either as its own function or within `CCM89`) within the scope of this package?

**Comment by karllark** [comment]
I'm not sure. Is the Conroy generalization for integrated measurements of galaxies and regions of galaxies?  Or for measurements of individual stars?   I have not read the paper yet, so figured I'd just ask!

If it is the the former (integrated measurements), then it should go in the dust_attenuation package. This would provide additional motivation to start this package.  I could easily setup all the structure for such a package soon, especially if someone were interested in working on adding attenuation models?

If it is the latter (extinction to single stars), then I would ask how this is different/better than the FM90 or P92 functions?  I haven't seen the motivation for this in the extinction curve measurement literature.  But I could easily have missed this.

**Comment by lea-hagen** [comment]
The Conroy paper is modeling attenuation curves, but they use their generalization of the extinction curve as an attenuation curve (section 3.2.1).  Since there's already a discussion of extinction vs attenuation over in #47, I'll just leave it at that.

I would certainly use a dust_attenuation package if it existed (though I'm still not convinced it should be separate).  I could probably even add some models!

**Comment by karllark** [comment]
We should put this model in the dust_attenuation package - it exists!
https://github.com/karllark/dust_attenuation

A variable bump in a CCM89 model is not really justified by dust extinction work.  For dust extinction curves, if the details of the 2175 A bump are of interest, then the FM90 or P92 formulation are generally used.

**Comment by karllark** [comment]
Created an issue for this model in the dust_attenuation package.

https://github.com/karllark/dust_attenuation/issues/28
