### ISSUE TITLE
extinction through filter

### ISSUE THREAD

**Issue by lea-hagen** [karllark/dust_extinction#57]
It would be nice to have the built-in functionality to feed in a filter bandpass (wavelength & transmission) and either A_V or E(B-V) to get the total extinction for a given extinction law.

The situation that made me think of this: going from E(B-V) of galactic foreground to the extinction in each of my filters.

**Comment by pllim** [comment]
Perhaps related to spacetelescope/synphot_refactor#132 . In `synphot`, you can apply extinction to filters, but just not with models from this package.

**Comment by karllark** [comment]
One complication, the effective extinction in a filter depends on the spectrum of the star.  But I agree, still would be useful.

Of course, right now all the extinction curves in the optical/NIR are based on filter photometry to derive the extinction curves.  So, just getting the extinction at the nominal filter wavelength will give you what you want.  This will change in the near future for the optical with new work (Fitzpatrick, Massa, Gordon, in prep).  And hopefully in the NIR and MIR soon too (Gordon et al. in prep).  Just gotta get the work done. :-)

**Comment by karllark** [comment]
This is beyond the scope of this package.
