### ISSUE TITLE
Split dust_extinction.py into smaller files

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#65]
All the module code is currently contained in the single dust_extinction.py file.  This makes for a fairly large file.  It would be more readable to have smaller, potentially one for each models.  The idea for a single file was that if it was ever incorporated into the astropy core, a single file would be what is needed.  Given the growth of this package, it does not seem likely that a move to astropy core will ever happen.  Hence, I am proposing that we split the large file into one per model and one with the classes that each model inherits.
Comments welcome!

**Comment by krislars** [comment]
Breaking the large file into smaller files might make it easier for contributors, too.  More than once I began editing the wrong model.  So I vote yes.

**Comment by karllark** [comment]
Ok.  I can take a try at this, possible even today if there is free time.

**Comment by karllark** [comment]
Have not worked on this yet.  But had more thoughts.

I am thinking that it would be better to not break things into one file per model as then the imports would look like:
`from dust_extinction.CCM89 import CCM89`

Instead, how about having 3 files for each type of model?  One for averages, one for parameter dependent averages, and one for shape fitting models.  The base classes for each type of model could go into the appropriate file with, possibly, one more file with any generic code that is used by multiple types of models.  The imports would then be:
`from dust_extinction.average_models import G03_SMCBar`
`from dust_extinction.parameter_average_models import F04`
`from dust_extinction.shape_models import FM90`
Not 100% happy with the names of the files/modules, but at least this gives the idea. Could also remove the 'models' string and just have `averages`, `parameter_averages`, and `shapes`.  I am leaning towards this as the names would be shorter.

Comments?

**Comment by karllark** [comment]
Working on this.  PR soon.
