### ISSUE TITLE
Add S07 class

### ISSUE THREAD

**Issue by thomaslai78226** [karllark/dust_extinction#68]
Adding S07 extinction curve from PAHFIT (Smith et al. 2007)

**Comment by karllark** [comment]
As we discussed during pyastro18, this S07 is an attenuation model as it has been tuned on galaxy spectra.  So should go into the dust_attenuation package instead of this package.

https://github.com/karllark/dust_attenuation

**Comment by karllark** [comment]
Issue moved to dust_attenuation repository.
https://github.com/karllark/dust_attenuation/issues/7
