### ISSUE TITLE
Astropy Affiliated Package Review

### ISSUE THREAD

**Issue by eteq** [karllark/dust_extinction#72]
This package has been reviewed by the Astropy coordination committee for inclusion in the Astropy affiliated package ecosystem. 

We have adopted a review process for affiliated package that includes assigning quantitative ‘scores’ (red/orange/green) for different categories of review. You can read up more about this process [here](https://docs.google.com/document/d/15PJf2PROXMa7xwTDvWnjXB_9KNuO2Ia4_kkxJ7MPazE/edit). (This document, currently in Google Docs, will be moved to the documentation in the near future.) For each of the categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.pch9wiwetm2l"><img src="https://img.shields.io/badge/Functionality-Specialized%20package-brightgreen.svg" alt="Specialized%20package"></a></td></tr>

<tr><td colspan=2><i>Strictly speaking this is generalized functionality because of course dust extinction is critical for pretty much all extragalactic astronomy.  But this particular *package* is primarily for the "expert" - even though some of its functionality is general I think it's best thought of as having a spcialist "target audience"?</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.lizp0k629jgg"><img src="https://img.shields.io/badge/Astropy%20integration-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Documentation</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.prawoqxdnwj5"><img src="https://img.shields.io/badge/Docs-Partial-orange.svg" alt="Partial"></a></td></tr>

<tr><td colspan=2><i>Sort of borderline between orange and green.  The examples/API are excellent, but the thing that is missing is a clear motivation/science background.  Obviously it's out-of-scope to write a ton on this, but because of the complexity of the topic, a bit more motivation of the *bounds* of this package and the intended user audience for various pieces might be helpful. </i></td></tr>

<tr><td><b>Testing</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.8dots8fmtpvp"><img src="https://img.shields.io/badge/Tests-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.zh2jxv4intgn"><img src="https://img.shields.io/badge/Development-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.9tur152fuipe"><img src="https://img.shields.io/badge/Python%203-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Other comments**

A great example of use of the package-template to speed development of a fundamentally science-based code.

**Summary/Decision**: Things are looking good! There are a few areas where things could be improved as described above. However, these aren't critical and this package still meets the criteria to be an affiliated package. Keep up the good work!

If you agree with the above review, please feel free to close this issue. If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review. Note that we are in the process of redesigning the http://affiliated.astropy.org page to show these scores (but not the comments). Finally, please keep the title of this issue as-is (“Astropy Affiliated Package Review”) to make it easy to search for affiliated package reviews in future.

**Comment by karllark** [comment]
Thanks for the review - great to see this package is on a good trajectory.

I would enjoy hearing more about how to make this useful to a wider less-expert community.  Putting in more background material is definitely a good idea.  Work on tutorials has also started.  Any other ideas/suggestions greatly appreciated.

One minor quibble.  I would say that this package is needed for most of astronomy, not just extragalactic.  All those stars in the MW are extinguished by dust of course.

**Comment by eteq** [comment]
> One minor quibble. I would say that this package is needed for most of astronomy, not just extragalactic. All those stars in the MW are extinguished by dust of course.

@karllark - absolutely I agree, this is sort of a grey zone - see the comment in the functionality/scope section.  Basically it seems to me like the target audience has two different groups: 1) "dust people" (i.e., those who care about dust for its own sake), and 2) people who think dust is just crud that gets in the way of what's really worth observing in the universe.  If the target is 1) it's specialized, if it's 2) it's general.  But I guess the answer is sort of in between.  I came down on "specialized" almost more as a way to *advertise* those who I expect to be your main contributors - those in 1).  But I could be convinced the other way if you have a strong opinion.

**Comment by karllark** [comment]
My goal is that the target audience is both the specialized user and the general user.  At least that is what I'd like.  I'm the specialized user, so need more feedback from general users on what is needed.   You've given a general user idea (spec1xd related code) and I have thought of others (e.g., the equivalent of the idl code ccm_unred.pro).  Need to document all such ideas and write the appropriate code.  

I'm fine with either designation for the affiliated docs.  But this does raise the question, is it possible to choose both?  :-)
