### ISSUE TITLE
New release (v0.7)?

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#82]
New models and new docs.  Time for a new release?
Remember to update CHANGES.rst.

**Comment by krislars** [comment]
I've always wondered how folks make this decision.  In this case, having new models would probably be one of the triggers.

I also wonder if you've thought about a publication or cite-able event.  AAS Research Note? AAS meeting poster? Zenodo?

**Comment by karllark** [comment]
Some kind of publication would be good.  We can definitely do Zenodo.  I've also been thinking about an article in JOSS (https://joss.theoj.org/).  Even have an issue for this #66.

I was thinking that right timing would be when we hit version v1.0.  I did create a milestone sometime ago for this version.  Not

https://github.com/karllark/dust_extinction/milestone/1

**Comment by karllark** [comment]
Definitely need to release a new version (see #83).

**Comment by karllark** [comment]
Just done!  Lots of changes since the last version.  Will need to make sure it is not so long till the next version.  :-)
