### ISSUE TITLE
Raise a warning if no units on input x

### ISSUE THREAD

**Issue by karllark** [karllark/dust_extinction#85]
Currently, if the user in puts x values without units, they are silently assumed to be in 1/micron units.  This should raise a standard warning stating this assumption.  This way the user will be made aware of the assumption, and can choose to silence the warnings if desired.

**Comment by krislars** [comment]
I'm having trouble with the warning showing up even when I'm using units.

This works without a warning:

    wav = np.arange(0.1, 3.0, 0.001)*u.micron
    for model in [CCM89]:
        for R in (2.0,3.0,4.0):
            # Initialize the extinction model
            ext = model(Rv=R)
            plt.plot(1/wav, ext(wav), label=model.name+' R='+str(R))

Same code with a different model throws a warning:

    wav = np.arange(0.1, 3.0, 0.001)*u.micron
    for model in [F99]:
        for R in (2.0,3.0,4.0):
            # Initialize the extinction model
            ext = model(Rv=R)
            plt.plot(1/wav, ext(wav), label=model.name+' R='+str(R))

Bug or WAD?

**Comment by karllark** [comment]
Sounds like a bug!

**Comment by karllark** [comment]
I think I've fixed this as part of consolidating code on this topic.  Now all of the models call the function `_get_x_in_wavenumbers` in helpers.py.
@krislars : can you check if this is true?

**Comment by karllark** [comment]
I have reproduced this problem.   So a bug.  I will see if I can find a solution.
